---
- name: Restart OTel Collector
  ansible.builtin.include_role:
    name: observability_common
    tasks_from: launchd_restart
  vars:
    launchd_service_label: com.observability.otelcol
    launchd_service_plist: /Library/LaunchDaemons/com.observability.otelcol.plist
