---
- name: Restart VictoriaMetrics
  ansible.builtin.include_role:
    name: observability_common
    tasks_from: launchd_restart
  vars:
    launchd_service_label: com.observability.victoriametrics
    launchd_service_plist: /Library/LaunchDaemons/com.observability.victoriametrics.plist

- name: Restart Grafana
  ansible.builtin.include_role:
    name: observability_common
    tasks_from: launchd_restart
  vars:
    launchd_service_label: com.observability.grafana
    launchd_service_plist: /Library/LaunchDaemons/com.observability.grafana.plist
