---
all:
  children:
    monitoring_server:
      hosts:
        monitoring-mac:
          ansible_host: REPLACE_WITH_SERVER_IP
          ansible_user: REPLACE_WITH_SSH_USER

    monitored_nodes:
      hosts:
        mac-mini-02:
          ansible_host: REPLACE_WITH_NODE2_IP
          ansible_user: REPLACE_WITH_SSH_USER
        mac-mini-03:
          ansible_host: REPLACE_WITH_NODE3_IP
          ansible_user: REPLACE_WITH_SSH_USER
